### ISSUE TITLE
Error accessing empty query string

### ISSUE THREAD

**Issue by jaguililla** [hexagonkt/hexagon#194]
Calling `Request.queryString` on a request with empty query string fails

```
java.lang.IllegalStateException: req.queryString must not be null
    at com.hexagonkt.http.server.servlet.Request.queryString(Request.kt:19)
    at com.hexagonkt.http.server.Request$queryString$2.invoke(Request.kt:23)
    at com.hexagonkt.http.server.Request$queryString$2.invoke(Request.kt:15)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at com.hexagonkt.http.server.Request.getQueryString(Request.kt)
```

**Comment by jaguililla** [comment]
Reported from previous version, fixed in 1.0
